image:
  file: .gitpod.dockerfile
ports:
- port: 3000 # Trace viewer example application
- port: 9229 # Node.js debug port
  onOpen: ignore
- port: 9339 # Node.js debug port
  onOpen: ignore
- port: 6080 # VNC server
  onOpen: ignore
- port: 5900
  onOpen: ignore
- port: 8080 # Trace Compass server
  onOpen: ignore
tasks:
- init: >
    yarn download:server
  command: >
    yarn start:server
- init: >
    yarn download:sample-traces &&
    yarn
  command: >
    yarn start:electron ../TraceCompassTutorialTraces/ --hostname=0.0.0.0
github:
  prebuilds:
    pullRequestsFromForks: true